server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        enable_lazy_load_no_trans: true

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: drogaria
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    token:
      secret-key: chave_microservices
      expire-length: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
