version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    #network_mode: "host"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    #network_mode: "host"
    env_file:
      - ./docker/grafana.env
    expose:
      - 3000
    ports:
      - "3000:3000"
